name: .NET

on:
  push:
    branches: [ master ]
    tags:
      - '*.*.*'
    workflow_dispatch:
  pull_request:
    branches: [ master ]

env:
  MINVERBUILDMETADATA: 


jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Tests
        path: '**/*.trx'    
        reporter: dotnet-trx
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: "**/*.trx"
    - name: Upload packages as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nuget packages
        path: "**/*.nupkg"
    - name: Push to GitHub Feed
      run: dotnet nuget push **/*.nupkg --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
    - name: Push to AppVeyor Feed
      run: dotnet nuget push **/*.nupkg --source https://ci.appveyor.com/nuget/openrasta/api/v2/package --api-key ${{ secrets.APPVEYOR_TOKEN }} --skip-duplicate


