name: .NET

on:
  push:
    branches: [ master ]
    tags:
      - '*.*.*'
    workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal 
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: "**/*.trx"
    - name: Upload packages as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nuget packages
        path: "**/*.nupkg"
    - name: Push to GitHub Feed
      run: dotnet nuget push **/*.nupkg --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
    - name: Push to AppVeyor Feed
      run: dotnet nuget push **/*.nupkg --source https://ci.appveyor.com/nuget/openrasta/api/v2/package --api-key ${APPVEYOR_TOKEN} --skip-duplicate
      env:
        APPVEYOR_TOKEN: ${{ secrets.APPVEYOR_TOKEN }}
